### PR TITLE
populate_dandiset_asset_yamls.py: Report conversion & validation errors

### LINKED ISSUE #5: script and committed/pushed results for validating metadata
Using https://github.com/dandi/dandi-cli/pull/379 of dandi-cli, script which would (given dataset paths, like in other scripts) run validation and store validation errors summary (which error happened in how many/which files) in `<dandiset>/VALIDATION.errors` (and remove that file if there is no errors in any file). FWIW it could be joined/hacked on top of the one from #4 since also needs to go file by file. Ideally that script should be extended to also produce `<dandiset>/CONVERSION.errors`.

Goals/purpose:
- identify sample dandisets which I could try uploading to dandi-api instance without failing validation
- then we could re-run it periodically and update the "status" for all dandisets and make it easy to identify what we need to fix either in metadata within files or in the schema.

### PR DESCRIPTION
**Pull request by jwodder**
Closes #5.

### CODE REVIEW

**Comment by yarikoptic** [comment]
To close #5 could you please include the actual run of the script and changes to all the `000*`?

**Comment by jwodder** [comment]
@yarikoptic The files created by running the script have been committed.

**Comment by satra** [comment]
@jwodder and @yarikoptic - i was wondering whether the assets could be put into a single assets.yaml file. the file would be long, but may make it easier to track diffs over time.

- the current identifier is the nwb object id. based on yarik's other PR, should we either remove it or change the asset identifier from UUID back to str
- since i can't really go through all the files. in the dandisets where there is subject id, age, genotype and other information, are these being added properly into the metadata (`wasDerivedFrom`)?

`wasDerivedFrom` is intended to be a chain of biosamples from cell id, slice id, tissuesample id, to subject id

alternatively we can collapse Biosample at present to include these properties.

**Comment by yarikoptic** [comment]
> @jwodder and @yarikoptic - i was wondering whether the assets could be put into a single assets.yaml file. the file would be long, but may make it easier to track diffs over time

not sure if it would actually make it easier -- now we could just rely on `git diff --stat` to see which/how many assets changed and plain `git diff` to see how.  With a single file per dandiset IMHO might only become more cumbersome.

edit: although a sheet number of files indeed would take checkout etc a bit longer, I think we would only benefit from individual files ... although checkout is indeed very slow -- I will see if indeed may be we are hitting some pragmatic trade-off, will report later, going food shopping now! (the most exciting event of the week leading to get "away from home" ;))

**Comment by yarikoptic** [comment]
thanks @jwodder  -- looks already very handy. We can improve as we go on.  Meanwhile some stats/listings:

<details>
<summary>14 dandisets with conversion erors</summary> 

```shell
$> ls -ld */CONVERSION.errors | nl        
     1	-rw------- 1 yoh yoh   79818 Feb 13 15:11 000006/CONVERSION.errors
     2	-rw------- 1 yoh yoh 1860246 Feb 13 15:13 000012/CONVERSION.errors
     3	-rw------- 1 yoh yoh   79531 Feb 13 15:13 000013/CONVERSION.errors
     4	-rw------- 1 yoh yoh  204525 Feb 13 15:13 000016/CONVERSION.errors
     5	-rw------- 1 yoh yoh   12233 Feb 13 15:13 000019/CONVERSION.errors
     6	-rw------- 1 yoh yoh 1373754 Feb 13 15:17 000021/CONVERSION.errors
     7	-rw------- 1 yoh yoh 1084863 Feb 13 15:17 000022/CONVERSION.errors
     8	-rw------- 1 yoh yoh    3876 Feb 13 15:17 000025/CONVERSION.errors
     9	-rw------- 1 yoh yoh   78733 Feb 13 15:17 000026/CONVERSION.errors
    10	-rw------- 1 yoh yoh    4632 Feb 13 15:17 000028/CONVERSION.errors
    11	-rw------- 1 yoh yoh    6040 Feb 13 15:17 000029/CONVERSION.errors
    12	-rw------- 1 yoh yoh    9094 Feb 13 15:17 000034/CONVERSION.errors
    13	-rw------- 1 yoh yoh 1207828 Feb 13 15:17 000045/CONVERSION.errors
    14	-rw------- 1 yoh yoh 1046387 Feb 13 15:22 000052/CONVERSION.errors

```
</details>

<details>
<summary>30 dandisets presumably without validation errors (but might be without assets) </summary> 

```shell
$> for d in 00*; do [ -e $d/VALIDATION.errors ] || echo $d; done | nl
     1	000006
     2	000008
     3	000012
     4	000013
     5	000016
     6	000018
     7	000021
     8	000022
     9	000024
    10	000025
    11	000026
    12	000028
    13	000030
    14	000031
    15	000032
    16	000033
    17	000034
    18	000035
    19	000038
    20	000040
    21	000042
    22	000044
    23	000045
    24	000046
    25	000047
    26	000052
    27	000054
    28	000055
    29	000056
    30	000057
```
</details>

<details>
<summary>14 with some sub-* and no  validation errors</summary> 

```shell
$> for d in 00*; do [ ! -e $d/VALIDATION.errors ] && /bin/ls $d/sub-* 2>/dev/null | grep -q . && echo $d; done | nl
     1	000006
     2	000008
     3	000012
     4	000013
     5	000016
     6	000021
     7	000022
     8	000028
     9	000034
    10	000035
    11	000044
    12	000045
    13	000055
    14	000056
```
</details>

<details>
<summary>5 without any errors and some sub-*</summary> 

```shell
$> for d in 00*; do [ ! -e $d/VALIDATION.errors ] && [ ! -e $d/CONVERSION.errors ] && /bin/ls $d/sub-* 2>/dev/null | grep -q . && echo $d; done | nl
     1	000008
     2	000035
     3	000044
     4	000055
     5	000056

```
</details>

**Comment by yarikoptic** [comment]
> * ince i can't really go through all the files. in the dandisets where there is subject id, age, genotype and other information, are these being added properly into the metadata (`wasDerivedFrom`)?
> 
> `wasDerivedFrom` is intended to be a chain of biosamples from cell id, slice id, tissuesample id, to subject id

yeah - ATM they are all empty, something to fix up
```
(git-annex)lena:~/proj/dandi/dandi-api-datasets[gh-5]git
$> git grep wasDerivedFrom | grep -v -e '\[\]'
(dev3) 1 57565 ->1.....................................:Sat 13 Feb 2021 08:24:18 PM EST:.
(git-annex)lena:~/proj/dandi/dandi-api-datasets[gh-5]git
$> git grep wasDerivedFrom | head             
000003/sub-YutaMouse20/sub-YutaMouse20_ses-YutaMouse20-140321_behavior+ecephys.nwb.yaml:wasDerivedFrom: []
000003/sub-YutaMouse20/sub-YutaMouse20_ses-YutaMouse20-140324_behavior+ecephys.nwb.yaml:wasDerivedFrom: []
...
```

**Pull request merged**
